#!/bin/bash
export MYSQLCLIENT_CFLAGS=`pkg-config mysqlclient --cflags`
export MYSQLCLIENT_LDFLAGS=`pkg-config mysqlclient --libs`
apt-get update
apt-get install -y python3-dev default-libmysqlclient-dev build-essential
apt-get install -y python3-pip
