#syntax=docker/dockerfile:1
FROM ubuntu:22.04

WORKDIR /opt/app
COPY ./flask_app .

RUN apt-get update && \
    apt-get install -y libmysqlclient-dev && \
    apt-get install -y python3 && \
    apt-get install -y python3-pip && \
    apt-get install -y pkg-config && \
    pip3 install -r requirements.txt

CMD ["python3", "app.py"]
